### ISSUE TITLE
IP location flag image not displaying (error 404)

### ISSUE THREAD

**Issue by LuckVintage** [FriendsOfFlarum/geoip#24]
For the last week or so I've noticed that the flag image no longer displays next to the user's IP Address - this is happening on two different Flarum installs on different servers. I am using the latest version of Flarum and the GeoIP extension. I chose the IP-API service in the extension's settings.

![image](https://user-images.githubusercontent.com/54641441/213300314-45b3020d-ced6-4bb3-a5ca-59d6018620f0.png)

I checked my browser console, and it appears the image failed to load because it doesn't exist anymore - is it possible to use a different source for the flag images?

![image](https://user-images.githubusercontent.com/54641441/213299981-c0130956-fcf1-437b-9544-c263e4fcfbf4.png)

Many Thanks.

**Comment by umutcandev** [comment]
I can reproduce this problem myself.
![IMG_20230312_014901](https://user-images.githubusercontent.com/96707573/224514878-fef2bfeb-edb4-46ca-b718-ce47171086d9.jpg)

**Comment by dsevillamartin** [comment]
Fixed in version `1.2.0`
